### ISSUE TITLE
Viable for practical use on strings? `Prefix` implementation for `String`/`&str`?

### ISSUE THREAD

**Issue by sdasda7777** [tiborschneider/prefix-trie#2]
Hi, do I understand correctly the provided structures could be used to find all strings with given prefix? Do you think in that case it would be possible to provide implementation of `Prefix` for some string type? Or are there perhaps some limitations making it not that useful with strings? Are there any other approaches/libraries you would recommend for finding strings with given prefix?

**Comment by tiborschneider** [comment]
This isn't designed for variable-sized data. Have a look at [radix-trie](https://crates.io/crates/radix_trie) or [trie-rs (LOUDS)](https://crates.io/crates/trie-rs), they are probably what you are looking for.

**Comment by sdasda7777** [comment]
I see, thanks!
